NAME = so_long

SRCS = game/draw.c game/errors.c game/game.c \
map_check/check_exit_maze.c map_check/check_items.c \
map_check/check_maze.c map_check/get_size.c \
map_check/init_map.c map_check/map_changes.c \
map_check/maze_exit.c map_check/save_map.c \

OBJS	= = $(SRCS:.c=.o)
//gcc main_prueba.c ../libft/libft.a -lmlx -framework OpenGL -framework AppKit