rush-02: ft_errors.o ft_str.o main.o
	cc -o -Wall -Wextra -Werror ft_errors.c ft_str.c main.c
ft_errors.o: ft_errors.c
	cc	-c -Wall -Wextra -Werror ft_errors.c 
ft_str.o: ft_str.c
	cc	-c -Wall -Wextra -Werror  ft_str.c
main.o: ft_main.c
	cc	-c -Wall -Wextra -Werror main.c
fclean:
	rm -f *.o
